CREATE CERTIFICATE ExampleCertificate
   ENCRYPTION BY PASSWORD = 'pGFD4bb925DGvbd2439587y' 
   WITH SUBJECT = 'Ejemplo de certificado',
   EXPIRY_DATE = '20201031';  
GO

CREATE ASYMMETRIC KEY ExampleKey
    WITH ALGORITHM = RSA_2048   
    ENCRYPTION BY PASSWORD = 'e3b0c44298fc1c149afbf4c8996fb9';   
GO  

CREATE LOGIN VICTOR 
	WITH PASSWORD = '2FEB19';
GO

CREATE USER VIC FOR LOGIN VICTOR;
GO

CREATE USER CARL FROM EXTERNAL PROVIDER;
GO

CREATE USER	BETTY WITHOUT LOGIN;
GO

CREATE USER TempUser FOR CERTIFICATE ExampleCertificate;
GO

CREATE USER KeyUser FROM ASYMMETRIC KEY ExampleKey;

